Forgot password aa
Awzel/Vytrack-front-end pull request #12
Opened 2024-03-25 21:16 UTC by Awzel

2024-03-25 22:36 UTC, Halzat113 commented
please create a new page for forgot password since when you click the 'forgot password link' redirects you to a new page

2024-03-25 23:15 UTC, Halzat113 requested changes

2024-03-26 00:26 UTC, Awzel commented on src/test/java/com/vytrack/stepdefs/LoginStepDef.java
> +        loginPage.forgotPasswordFailedMsg.isDisplayed();
Great point! Done!

2024-03-26 00:31 UTC, Awzel commented
I've made some changes, take a look and please let me know if anything!

2024-03-26 00:56 UTC, Halzat113 approved these changes

2024-03-26 00:56 UTC, merged